stav_svc_feature-completed, client with RestTemplate, tests for client
DusynHub/java-explore-with-me pull request #1
Opened 2023-06-02 22:34 UTC by DusynHub

2023-06-03 13:15 UTC, AnastasiyaFomkina requested changes

2023-06-03 13:15 UTC, AnastasiyaFomkina commented on stats-module/stats-server-module/pom.xml
> +			<artifactId>mockito-junit-jupiter</artifactId>
Нужно удалить все лишние зависимости из данного модуля. В нем обозначены только сущности, для которых тестовые, sql и мапстракт зависимости уж точно не нужны

2023-06-03 13:15 UTC, AnastasiyaFomkina commented on stats-module/stats-server-module/src/main/java/ru/practicum/server/mapper/EndpointHitMapper.java
> +    EndpointHitMapper INSTANCE = Mappers.getMapper(EndpointHitMapper.class);
Нужно подключать через `dependency injection`, как и любой другой компонент спинга, не зря мы выше обозначили, что маппер должен быть компонентом

2023-06-03 13:15 UTC, AnastasiyaFomkina commented on stats-module/stats-server-module/src/main/java/ru/practicum/server/service/StatsServerServiceImpl.java
> +    private static final QEndpointHit qEndpointHit = QEndpointHit.endpointHit;
Не очень похоже на то, что код компилируется. Класса `QEndpointHit` нет в пакете `ru.practicum.common.stats.model`

2023-06-03 13:15 UTC, AnastasiyaFomkina commented on stats-module/stats-server-module/src/main/java/ru/practicum/server/service/StatsServerServiceImpl.java
> +            byUri = qEndpointHit.uri.notIn(endpoints);
Доступ к полям модели должен быть строго через геттеры. Все поля моделей должны быть максимально защищены от изменений

2023-06-03 13:15 UTC, AnastasiyaFomkina commented on stats-module/stats-server-module/src/main/java/ru/practicum/server/service/StatsServerServiceImpl.java
> +    private final StatsServiceRepository statsServiceRepository;
Зачем тебе одновременно `entityManager` и `SpringData` репозиторий? Нужно выбрать один подход взаимодействия с бд и следовать ему

2023-06-04 16:40 UTC, DusynHub commented on stats-module/stats-client-module/src/main/java/ru/practicum/stats/client/StatsClient.java
> +@Component
Удалил клиента на основе RestTemplate. Переписал полностью заново.

2023-06-04 16:40 UTC, DusynHub commented on stats-module/stats-client-module/src/main/java/ru/practicum/stats/client/StatsClient.java
> +    private final String statsServerUrl = "http://localhost:9090";
Удалил клиента на основе RestTemplate. Переписал полностью заново.

2023-06-04 16:40 UTC, DusynHub commented on stats-module/stats-client-module/src/main/resources/application.properties
Удалил неиспользуемую папку

2023-06-04 16:41 UTC, DusynHub commented on stats-module/stats-client-module/src/test/java/ru/practicum/stats/client/StatsClientTest.java
> +            new StringBuilder()
Вместо StringBuilder использовал UriComponentsBuilder

2023-06-04 16:41 UTC, DusynHub commented on stats-module/stats-client-module/src/test/java/ru/practicum/stats/client/StatsClientTest.java
> +                .when(
Исправил отступы

2023-06-04 16:41 UTC, DusynHub commented on stats-module/stats-common-dto-module/src/main/resources/application.properties
Удалил свойства и папку ресурсы

2023-06-04 16:42 UTC, DusynHub commented on stats-module/stats-server-module/pom.xml
> +			<artifactId>mockito-junit-jupiter</artifactId>
Постарался удалить все лишние зависимости и всех `pom` файлов

2023-06-04 16:43 UTC, DusynHub commented on stats-module/stats-server-module/src/main/java/ru/practicum/server/mapper/EndpointHitMapper.java
> +    EndpointHitMapper INSTANCE = Mappers.getMapper(EndpointHitMapper.class);
Маппер удалил из-за отсутвтия необходимости при использовании EntityManager.

Но этого замечания не понял. Нужно INSTANCE тожее через  `dependency injection` вставлять?

2023-06-04 16:44 UTC, DusynHub commented on stats-module/stats-server-module/src/main/java/ru/practicum/server/service/StatsServerServiceImpl.java
> +    private static final QEndpointHit qEndpointHit = QEndpointHit.endpointHit;
![image](https://github.com/DusynHub/java-explore-with-me/assets/112579759/c5f7528e-b469-43dc-91ae-c16b403a5a8f)

Вроде генерируется

2023-06-04 16:45 UTC, DusynHub commented on stats-module/stats-server-module/src/main/java/ru/practicum/server/service/StatsServerServiceImpl.java
> +            byUri = qEndpointHit.uri.notIn(endpoints);
К сожалению не очень понимаю сути замечания. Все поля ДТО и сущностей имею приватные поля.

2023-06-04 16:45 UTC, DusynHub commented on stats-module/stats-server-module/src/main/java/ru/practicum/server/service/StatsServerServiceImpl.java
> +    private final StatsServiceRepository statsServiceRepository;
Оставил только использование entityManager. 

Правда не понял как правильно возвращать вставленную сущность при использовании entityManager.
Пришлось делать второй запрос на выборку конкретной строки. Это корректный подход?

Сделать insert с использованием QueryDsl не вышло.  Запрос проходил, но вставки не просиходило. Вероятно с DataSource ошибся.

Вообще целесообразно использовать QueryDsl или лучше JPQL и SpringData использовать?

2023-06-04 22:23 UTC, AnastasiyaFomkina commented on stats-module/stats-server-module/src/main/java/ru/practicum/server/service/StatsServerServiceImpl.java
> +    private final StatsServiceRepository statsServiceRepository;
Я бы выбрала SpringData, потому что тут не сильно большой проект, который не подразумевает больших данных и сложных запросов. Но оба похода - ок

2023-06-04 22:29 UTC, AnastasiyaFomkina commented on stats-module/stats-server-module/src/main/java/ru/practicum/server/service/StatsServerServiceImpl.java
> +            byUri = qEndpointHit.uri.notIn(endpoints);
`qEndpointHit.uri` - доступ напрямую к полю метода, так как он public
![Uploading Снимок экрана 2023-06-04 в 19.28.04.png…]()

2023-06-04 22:32 UTC, AnastasiyaFomkina commented on stats-module/stats-server-module/src/main/java/ru/practicum/server/service/StatsServerServiceImpl.java
> +            byUri = qEndpointHit.uri.notIn(endpoints);
Мой косяк, забыла, что это queryDSL, он генерить публичные поля без геттеров

2023-06-04 22:34 UTC, AnastasiyaFomkina commented on stats-module/stats-server-module/src/main/java/ru/practicum/server/service/StatsServerServiceImpl.java
> +    private static final QEndpointHit qEndpointHit = QEndpointHit.endpointHit;
Видимо где-то недогенерила проект :(

2023-06-04 22:35 UTC, AnastasiyaFomkina commented on stats-module/stats-server-module/src/main/java/ru/practicum/server/mapper/EndpointHitMapper.java
> +    EndpointHitMapper INSTANCE = Mappers.getMapper(EndpointHitMapper.class);
Сам маппер можно подключать, как спринг - бин, так как он генерируется с аннотацией `@Component`. Соответственно INSTANCE создавать не нужно вообще

2023-06-04 22:38 UTC, AnastasiyaFomkina approved these changes

2023-06-05 14:09 UTC, merged