Version 1.0.0
DusynHub/java-explore-with-me pull request #2
Opened 2023-06-17 01:10 UTC by DusynHub

2023-06-17 23:27 UTC, AnastasiyaFomkina requested changes

2023-06-17 23:27 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/ewm/category/model/dto/CategoryMapper.java
> +    CategoryMapper INSTANCE = Mappers.getMapper(CategoryMapper.class);
Лучше подключать мапперы с помошью [dependency injection](https://reflectoring.io/java-mapping-with-mapstruct/#:~:text=the%20same%20time.-,Dependency%20Injection,-If%20we%20want), так как у нас спринговый проект

2023-06-17 23:27 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/ewm/enums/State.java
> +        if (stateAction == StateAction.PUBLISH_EVENT) {
Тут ты явно завязался на другое перечисление, поэтому нужно будет не забывать поддерживать одновременно их оба. 
Лучше добавить в `StateAction` параметр `actionName`, а здесь добавить метод получения `enum` из строки, так мы избавимся от явной связи `State` и `StateAction`.
Вот [здесь](https://metanit.com/java/tutorial/3.8.php#:~:text=%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D0%BE%D1%80%D1%8B%2C%20%D0%BF%D0%BE%D0%BB%D1%8F%20%D0%B8%20%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B%20%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F) можно посмотреть про переменные в enum

2023-06-17 23:27 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/ewm/event/controller/PublicEventController.java
> +        log.info("endpoint path: {}", request.getRequestURI());
На 72 и 73 строке лучше заменить уровень логирования на `debug`, так как данная информация более информативна для дебага. Лучше еще объединить их в один лог

2023-06-17 23:27 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/ewm/event/model/Event.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
Лучше вынести паттерн в публичную константу и переспользовать ее по всему модулю

2023-06-17 23:27 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +        Map<Long, CategoryDto> categoryDtos = categoryService.findAllById(categoryIds)
Код со строк 440 - 455 дублируется на строках 470-484. Нужно избавиться от дублирований кода

2023-06-19 09:27 UTC, AnastasiyaFomkina requested changes
Осталось совсем чуть-чуть

2023-06-19 09:27 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/ewm/enums/State.java
> +    public static State getStateFromStateAction(String stateAction) {
Это не совсем то, что я имела ввиду. Теперь ты явно завязался на определенные строки, поэтому этот метод будет расти с каждым разом все больше и больше. 
Нужно было добавить дополнительную переменную в `StateAction`. Можно даже сделать еще проще и вместо строки, сделать переменную сразу нужным нам перечислением:
```
package ru.practicum.ewm.enums;

public enum StateAction {

    PUBLISH_EVENT(State.PUBLISHED),
    REJECT_EVENT(State.CANCELED),
    CANCEL_REVIEW(State.CANCELED),
    SEND_TO_REVIEW(State.PENDING);

    private final State state;

    StateAction(State state) {
        this.state = state;
    }

    public State getState() {
        return state;
    }

    public static StateAction getStateAction(String potentialStateAction) {
        try {
            return StateAction.valueOf(potentialStateAction);
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("Unknown state: UNSUPPORTED_STATE_ACTION");
        }
    }
}

```
Так нам не придется постоянно поддерживать этот раздувающийся метод и у нас уже будет готовая связка двух действий

Соответственно использоваться будет вот так
```
updatedState = StateAction.getStateAction(updateEventRequest.getStateAction()).getState();
```

2023-06-19 16:17 UTC, DusynHub commented on ewm-service/src/main/java/ru/practicum/ewm/enums/State.java
> +    public static State getStateFromStateAction(String stateAction) {
Понял в чём дело. Если я использовал бы метод, то мог получать неподдерживаемое State, а при внедрении в виде поля у меня по сути получилось одно большое Enum. Спасибо за явное указание. Сам бы не додумался.

2023-06-20 08:40 UTC, merged