Feature comments
DusynHub/java-explore-with-me pull request #3
Opened 2023-06-21 20:53 UTC by DusynHub

2023-06-21 23:23 UTC, AnastasiyaFomkina requested changes
Отличная реализация - молодец 🔥

2023-06-21 23:23 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/ewm/comment/controller/PrivateCommentController.java
> +        newCommentDto.setCommentedEvent(eventId);
Во всех методах новых контроллеров нужно оставить только логирование и вызов сервиса, все остальное является бизнес-логикой и должно находиться в слое-сервисе

2023-06-21 23:23 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/ewm/comment/model/dto/CommentMapper.java
> +@Service
`componentModel = "spring"` генерирует  аннотацию `@Component` над имплементацией, поэтому `@Service` над интерфейсом - лишний

2023-06-23 13:22 UTC, DusynHub commented on ewm-service/src/main/java/ru/practicum/ewm/comment/model/dto/CommentMapper.java
> +@Service
Добавил доп аннотация, так как IDEA иначе не может опознать
![image](https://github.com/DusynHub/java-explore-with-me/assets/112579759/9b93d675-a0a7-4781-89ad-72b50a974bbf)

2023-06-23 13:31 UTC, DusynHub commented on ewm-service/src/main/java/ru/practicum/ewm/comment/controller/PrivateCommentController.java
> +        newCommentDto.setCommentedEvent(eventId);
Вынес всю логику на уровень сервиса

2023-06-24 12:52 UTC, AnastasiyaFomkina approved these changes

2023-06-30 16:41 UTC, merged